# Generated by Django 3.2.4 on 2021-06-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.TextField(max_length=100)),
                ('age_group', models.SmallIntegerField()),
                ('minutes', models.SmallIntegerField()),
                ('seconds', models.SmallIntegerField()),
                ('miliseconds', models.SmallIntegerField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Female', max_length=50)),
            ],
        ),
    ]
