# Generated by Django 3.2.4 on 2021-06-24 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_dashboard', '0004_alter_result_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='datecompleted',
        ),
        migrations.AddField(
            model_name='result',
            name='date_completed',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='run_image',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
