# Generated by Django 3.2.4 on 2021-07-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_dashboard', '0007_rename_run_image_result_run_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='age_group',
            field=models.CharField(choices=[('Under 25', 'Under 25'), ('26-35', '26-35'), ('36-49', '36-49'), ('50+', '50+')], default='26-35', max_length=50),
        ),
        migrations.AlterField(
            model_name='result',
            name='run_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
